name: flutter_bibi
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
assets:
  - images/
  - assets/
dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  cupertino_icons: ^1.0.2
  json_annotation: ^3.1.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  build_runner: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
#    - assets/